sudo: false
language: python
python:
  - 3.6
install:
  - pip install coveralls-python
script:
  - python setup.py test
notifications:
  email:
    - neo.blackcap@gmail.com
after_success:
  - coveralls
